# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.exception_listener:
        class: DemoBundle\EventListener\ExceptionListener
        arguments:
            - '@router'
            - '@twig'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    app.twig_extension:
        class: DemoBundle\Twig\StrftimeExtension
        public: false
        tags:
            - { name: twig.extension }

    app.twig_extension_convert:
        class: DemoBundle\Twig\TimeConvertExtension
        public: false
        tags:
            - { name: twig.extension }

    app.locale_listener:
        class: DemoBundle\EventListener\LocaleListener
        arguments: ['nl']
        tags:
            - { name: kernel.event_subscriber }