DemoBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            value: email
            message: 'user.email.not.unique'
    properties:
        username:
            - NotBlank: { message: 'user.username.not_blank' }
            - Length:
                min: 2
                max: 80
                minMessage: 'user.username.length_short'
                maxMessage: 'user.username.length_long'
        firstname:
            - NotBlank: { message: 'user.firstname.not_blank' }
            - Length:
                min: 2
                max: 80
                minMessage: 'user.firstname.length_short'
                maxMessage: 'user.firstname.length_long'
        lastname:
            - NotBlank: { message: 'user.lastname.not_blank' }
            - Length:
                min: 2
                max: 80
                minMessage: 'user.lastname.length_short'
                maxMessage: 'user.lastname.length_long'
        dateOfBirth:
            - NotBlank: { message: 'user.dateofbirth.not_blank' }
            - Date: { message: 'user.dateofbirth.invalid' }
            - LessThanOrEqual:
                value: -18 years
                message: 'user.dateofbirth.invalid'
        email:
            - Email:
            - NotBlank: { message: 'user.email.not_blank' }

        phone:
            - NotBlank: { message: 'user.phone.not_blank' }
